---
- name: Create a neutrons1 centos container
  lxc_container:
    name: neutrons1
    template: centos.mod
    state: stopped
    container_command: |
      sed -i 's/dhcp/none/g' /etc/sysconfig/network-scripts/ifcfg-eth0
      ssh-keygen -N "" -f ~/.ssh/id_rsa
    container_config:
      - "lxc.network.link = br0"
      - "lxc.network.veth.pair = neutrons1_eth0"
      - "lxc.network.ipv4.gateway = 192.168.242.1"
      - "lxc.network.ipv4 = 192.168.242.214/24"
      - "lxc.pts = 1024"
      - "lxc.kmsg = 0"


- name: copy our authorized_key file into place
  copy: src=authorized_keys dest=/var/lib/lxc/neutrons1/rootfs/root/.ssh/authorized_keys mode=0600

- name: Start a container
  lxc_container:
    name: neutrons1
    state: started

- name: Create a neutrons2 centos container
  lxc_container:
    name: neutrons2
    template: centos.mod
    state: stopped
    container_command: |
      sed -i 's/dhcp/none/g' /etc/sysconfig/network-scripts/ifcfg-eth0
      ssh-keygen -N "" -f ~/.ssh/id_rsa
    container_config:
      - "lxc.network.link = br0"
      - "lxc.network.veth.pair = neutrons2_eth0"
      - "lxc.network.ipv4.gateway = 192.168.242.1"
      - "lxc.network.ipv4 = 192.168.242.215/24"
      - "lxc.pts = 1024"
      - "lxc.kmsg = 0"


- name: copy our authorized_key file into place
  copy: src=authorized_keys dest=/var/lib/lxc/neutrons2/rootfs/root/.ssh/authorized_keys mode=0600

- name: Start a container
  lxc_container:
    name: neutrons2
    state: started

